# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.2 on 2018-03-05 11:19
=======
# Generated by Django 1.10.2 on 2017-11-17 10:03
>>>>>>> 21d2133523f10106670dd8c247d92d9339ee1b8b
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centro', '0006_auto_20161106_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Abr', models.CharField(max_length=4)),
                ('Nombre', models.CharField(max_length=50)),
                ('Unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centro.Cursos')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
    ]
